company/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = "company"

urlpatterns = [
    path('login/', views.company_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.company_signup, name="signup"),
    path('my-profile/', views.my_profile, name="my_profile"),
    path('photo-upload/', views.photo_upload, name="photo_upload"),
    path(
        'delete-avatar/',
        views.delete_avatar,
        name="delete_avatar"
    ),
    path('create-job/', views.create_post, name="create_post"),
    path('my-jobs/', views.my_posts, name="my_posts"),
    path('requests/', views.requests, name='request'),

    re_path(r'^my-jobs/(?P<pk>.*)/$', views.my_job, name="my_job"),
    re_path(r'^edit-job/(?P<pk>.*)/$', views.edit_post, name="edit_post"),
    re_path(r'^delete-job/(?P<pk>.*)/$', views.delete_job, name="delete_job"),
    re_path(
        r'^approve-request/(?P<pk>.*)/$',
        views.approve_request,
        name="approve_request"
    ),
    re_path(
        r'^decline-request/(?P<pk>.*)/$',
        views.decline_request,
        name="decline_request"
    ),
]

fiveM/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings
from main import views as general_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('web.urls', 'web')),
    path('app/', general_views.app, name='app'),

    path('app/accounts/', include('users.urls', namespace='users')),
    path('app/company/', include('company.urls', namespace='company')),

    re_path(
        'media/(?P<path>.*)$',
        serve,
        {'document_root': settings.MEDIA_ROOT}
    ),
    re_path(
        'static/(?P<path>.*)$',
        serve,
        {'document_root': settings.STATIC_FILE_ROOT}
    ),
]

users/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.enter, name="enter"),
    path('logout/', views.user_logout, name="user_logout"),
    path('edit/', views.edit_profile, name="edit_profile"),
    path('my-profile/', views.my_profile, name="my_profile"),
    path('photo-upload/', views.photo_upload, name="photo_upload"),
    path(
        'delete-avatar/',
        views.delete_avatar,
        name="delete_avatar"
    ),

    re_path(r'^save-job/(?P<pk>.*)/$', views.save_job, name="save_job"),
    re_path(r'^apply-job/(?P<pk>.*)/$', views.apply_job, name="apply_job"),
    re_path(r'^verify/(?P<pk>.*)/$', views.verify, name="verify"),
    re_path(r'^resend-otp/(?P<pk>.*)/$', views.resend_otp, name="resend_otp"),
]

web/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('contact-us/', views.contact, name="contact"),

    re_path(
        r'^job-details/(?P<pk>.*)/$',
        views.job_details,
        name="job_details",
    ),
]

templates/dashboard/includes/nav.html
{% load static %}
<ul class="main-menu">
    <li> 
        <a class="dashboard2 {% if is_dashboard %} active {% endif %}" href="{% url 'company:dashboard' %}">
        <img src="{% static 'dashboard/assets/imgs/page/dashboard/dashboard.svg' %}" alt="fiveM">
        <span class="name">Dashboard</span>
        </a>
    </li>
    <li> 
        <a class="dashboard2 {% if is_request %} active {% endif %}" href="{% url 'company:request' %}">
        <img src="{% static 'dashboard/assets/imgs/page/dashboard/candidates.svg' %}" alt="fiveM">
        <span class="name">Request</span>
        </a>
    </li>
    <!-- <li> 
        <a class="dashboard2 {% if is_dashboard %} active {% endif %}" href="">
        <img src="{% static 'dashboard/assets/imgs/page/dashboard/recruiters.svg' %}" alt="fiveM">
        <span class="name">Recruiters</span>
        </a>
    </li> -->
    <li> 
        <a class="dashboard2 {% if is_my_jobs %} active {% endif %}" href="{% url 'company:my_posts' %}">
        <img src="{% static 'dashboard/assets/imgs/page/dashboard/jobs.svg' %}" alt="fiveM">
        <span class="name">My Jobs</span>
        </a>
    </li>
    <!-- <li> 
        <a class="dashboard2 {% if is_dashboard %} active {% endif %}" href="">
        <img src="{% static 'dashboard/assets/imgs/page/dashboard/tasks.svg' %}" alt="fiveM">
        <span class="name">Tasks List</span>
        </a>
    </li> -->
    <li> 
        <a class="dashboard2 {% if is_my_profile %} active {% endif %}" href="{% url 'company:my_profile' %}">
        <img src="{% static 'dashboard/assets/imgs/page/dashboard/profiles.svg' %}" alt="fiveM">
        <span class="name">My Profiles</span>
        </a>
    </li>
    <!-- <li> 
        <a class="dashboard2 {% if is_dashboard %} active {% endif %}" href="">
        <img src="{% static 'dashboard/assets/imgs/page/dashboard/cv-manage.svg' %}" alt="fi
        veM"><span class="name">CV Manage</span>
        </a>
    </li> -->
    <!-- <li> 
        <a class="dashboard2 {% if is_dashboard %} active {% endif %}" href="">
        <img src="{% static 'dashboard/assets/imgs/page/dashboard/settings.svg' %}" alt="fiveM">
        <span class="name">Setting</span>
        </a>
    </li> -->
    <li> 
        <a class="dashboard2 {% if is_change_password %} active {% endif %}" href="">
        <img src="{% static 'dashboard/assets/imgs/page/dashboard/authentication.svg' %}" alt="fiveM">
        <span class="name">Change Password</span>
        </a>
    </li>
    <li> 
        <a class="dashboard2" href="{% url 'users:user_logout' %}">
        <img src="{% static 'dashboard/assets/imgs/page/dashboard/logout.svg' %}" alt="fiveM">
        <span class="name">Logout</span>
        </a>
    </li>
</ul>