fiveM/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings
from main import views as general_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('web.urls', 'web')),
    path('app/', general_views.app, name='app'),

    path('app/accounts/', include('users.urls', namespace='users')),
    path('app/company/', include('company.urls', namespace='company')),

    re_path(
        'media/(?P<path>.*)$',
        serve,
        {'document_root': settings.MEDIA_ROOT}
    ),
    re_path(
        'static/(?P<path>.*)$',
        serve,
        {'document_root': settings.STATIC_FILE_ROOT}
    ),
]

users/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.enter, name="enter"),
    path('logout/', views.user_logout, name="user_logout"),
    path('edit/', views.edit_profile, name="edit_profile"),
    path('my-profile/', views.my_profile, name="my_profile"),
    path('photo-upload/', views.photo_upload, name="photo_upload"),
    path(
        'delete-avatar/',
        views.delete_avatar,
        name="delete_avatar"
    ),

    re_path(r'^save-job/(?P<pk>.*)/$', views.save_job, name="save_job"),
    re_path(r'^apply-job/(?P<pk>.*)/$', views.apply_job, name="apply_job"),
    re_path(r'^verify/(?P<pk>.*)/$', views.verify, name="verify"),
    re_path(r'^resend-otp/(?P<pk>.*)/$', views.resend_otp, name="resend_otp"),
]

web/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('contact-us/', views.contact, name="contact"),

    re_path(
        r'^job-details/(?P<pk>.*)/$',
        views.job_details,
        name="job_details",
    ),
]

templates/web/contact.html
{% extends "web/base.html" %}
{% load static %}

{% block content %}
<main class="main">
    <section class="section-box">
      <div class="breacrumb-cover bg-img-about">
        <div class="container">
          <div class="row">
            <div class="col-lg-6">
              <h2 class="mb-10">Contact Us</h2>
              <p class="font-lg color-text-paragraph-2">Get the latest news, updates and tips</p>
            </div>
            <div class="col-lg-6 text-lg-end">
              <ul class="breadcrumbs mt-40">
                <li><a class="home-icon" href="{% url 'web:index' %}">Home</a></li>
                <li>Contact Us</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="section-box mt-80">
        <div class="container">
          <div class="box-info-contact">
            <div class="row">
              <div class="col-lg-3 col-md-6 col-sm-12 mb-30">
                <a href="#"><img src="{% static 'assets/imgs/page/contact/logo.svg' %}" alt="fiveM"></a>
                <div class="font-sm color-text-paragraph">205 Sulthan Bathery, Suite 810 North, 673579, Wayanad<br> Phone: +91 9895513875<br> Email: <a href="#" class="__cf_email__" data-cfemail="f99a96978d989a8db993969b9b9681d79a9694">&#160;fiveminutes@gmail.com</a></div><a class="text-uppercase color-brand-2 link-map" href="#">View map</a>
              </div>
              <div class="col-lg-3 col-md-6 col-sm-12 mb-30">
                <h6>London</h6>
                <p class="font-sm color-text-paragraph mb-20">2118 Thornridge Cir. Syracuse,<br class="d-none d-lg-block"> Connecticut 35624</p>
                <h6>New York</h6>
                <p class="font-sm color-text-paragraph mb-20">4517 Washington Ave.<br class="d-none d-lg-block"> Manchester, Kentucky 39495</p>
              </div>
              <div class="col-lg-3 col-md-6 col-sm-12 mb-30">
                <h6>Chicago</h6>
                <p class="font-sm color-text-paragraph mb-20">3891 Ranchview Dr. Richardson,<br class="d-none d-lg-block"> California 62639</p>
                <h6>San Francisco</h6>
                <p class="font-sm color-text-paragraph mb-20">4140 Parker Rd. Allentown,<br class="d-none d-lg-block"> New Mexico 31134</p>
              </div>
              <div class="col-lg-3 col-md-6 col-sm-12 mb-30">
                <h6>Sysney</h6>
                <p class="font-sm color-text-paragraph mb-20">3891 Ranchview Dr. Richardson,<br class="d-none d-lg-block"> California 62639</p>
                <h6>Singapore</h6>
                <p class="font-sm color-text-paragraph mb-20">4140 Parker Rd. Allentown,<br class="d-none d-lg-block"> New Mexico 31134</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section class="section-box mt-70">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 mb-40"><span class="font-md color-brand-2 mt-20 d-inline-block">Contact us</span>
              <h2 class="mt-5 mb-10">Get in touch</h2>
              <p class="font-md color-text-paragraph-2">The right move at the right time saves your investment. live<br class="d-none d-lg-block"> the dream of expanding your business.</p>
              <form class="contact-form-style mt-30" id="contact-form" action="." method="post">
                {% csrf_token %}
                <div class="row wow animate__animated animate__fadeInUp" data-wow-delay=".1s">
                  <div class="col-lg-6 col-md-6">
                    <div class="input-style mb-20">
                      <input class="font-sm color-text-paragraph-2" name="name" placeholder="Enter your name" type="text">
                    </div>
                  </div>
                  <div class="col-lg-6 col-md-6">
                    <div class="input-style mb-20">
                      <input class="font-sm color-text-paragraph-2" name="company" placeholder="Comapy (optioanl)" type="text">
                    </div>
                  </div>
                  <div class="col-lg-6 col-md-6">
                    <div class="input-style mb-20">
                      <input class="font-sm color-text-paragraph-2" name="email" placeholder="Your email" type="email">
                    </div>
                  </div>
                  <div class="col-lg-6 col-md-6">
                    <div class="input-style mb-20">
                      <input class="font-sm color-text-paragraph-2" name="phone" placeholder="Phone number" type="tel">
                    </div>
                  </div>
                  <div class="col-lg-12 col-md-12">
                    <div class="textarea-style mb-30">
                      <textarea class="font-sm color-text-paragraph-2" name="message" placeholder="Tell us about yourself"></textarea>
                    </div>
                    <button class="submit btn btn-send-message" type="submit">Send message</button>
                    <label class="ml-20">
                      <input class="float-start mr-5 mt-6" type="checkbox"> By clicking contact us button, you agree our terms and policy,
                    </label>
                  </div>
                </div>
              </form>
              <p class="form-messege"></p>
            </div>
            <div class="col-lg-4 text-center d-none d-lg-block"><img src="{% static 'assets/imgs/page/contact/img.png' %}" alt="fiveM"></div>
          </div>
        </div>
      </section>
  </main>
{% endblock %}

templates/web/job-details.html
{% extends "web/base.html" %}
{% load static %}
{% load main_template_tags %}

{% block content %}
<main class="main">
  <section class="section-box-2">
    <div class="container">
      <div class="banner-hero banner-image-single">
        <img src="{% static 'assets/imgs/page/job-single/thumb.png' %}" alt="fiveM">
      </div>
      <div class="row mt-10">
        <div class="col-lg-8 col-md-12">
          <h3>{{ instance.job_title }}</h3>
          <div class="mt-0 mb-15">
            <span class="card-briefcase">
              {% if instance.job_type == 'freelancer' %}
                Freelancer
              {% else %}
                Fulltime
              {% endif %}
            </span>
            <span class="card-time">{{ instance.post_date|time_until }}</span>
          </div>
        </div>
        <div class="col-lg-4 col-md-12 text-lg-end">
          <a class="action-button reload btn btn-apply-icon btn-apply-big hover-up" href="{% url 'users:apply_job' pk=instance.pk %}" data-id="" data-text="{{confirm_apply_message}}" data-title="Are you sure?">Apply now</a>
        </div>
        <div class="col-xl-7 col-md-7 mb-2">
          {% for i in instance.skills|comma_separator %}
            <b class="btn btn-tags-sm mr-5">{{i}}</b>
          {% endfor %}
        </div>
      </div>
      <div class="border-bottom pt-10 pb-10"></div>
    </div>
  </section>
  <section class="section-box mt-50">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-12 col-sm-12 col-12">
          <div class="job-overview">
            <h5 class="border-bottom pb-15 mb-30">Employment Information</h5>
            <div class="row">
              <div class="col-md-6 d-flex">
                <div class="sidebar-icon-item">
                  <img src="{% static 'assets/imgs/page/job-single/industry.svg' %}" alt="fiveM">
                </div>
                <div class="sidebar-text-info ml-10">
                  <span class="text-description industry-icon mb-10">Industry</span>
                  <strong class="small-heading"> {{ instance.industry }}</strong>
                </div>
              </div>
              <div class="col-md-6 d-flex mt-sm-15">
                <div class="sidebar-icon-item">
                  <img src="{% static 'assets/imgs/page/job-single/job-level.svg' %}" alt="fiveM">
                </div>
                <div class="sidebar-text-info ml-10">
                  <span class="text-description joblevel-icon mb-10">Job level</span>
                  <strong class="small-heading">{{ instance.job_level }}</strong>
                </div>
              </div>
            </div>
            <div class="row mt-25">
              <div class="col-md-6 d-flex mt-sm-15">
                <div class="sidebar-icon-item">
                  <img src="{% static 'assets/imgs/page/job-single/salary.svg' %}" alt="fiveM">
                </div>
                <div class="sidebar-text-info ml-10">
                  <span class="text-description salary-icon mb-10">Salary</span>
                  <strong class="small-heading">₹{{instance.amnt_start_per_hrs}} - ₹{{instance.amnt_end_per_hrs}}</strong>
                </div>
              </div>
              <div class="col-md-6 d-flex">
                <div class="sidebar-icon-item">
                  <img src="{% static 'assets/imgs/page/job-single/experience.svg' %}" alt="fiveM">
                </div>
                <div class="sidebar-text-info ml-10">
                  <span class="text-description experience-icon mb-10">Experience</span>
                  <strong class="small-heading">{{instance.experience}}</strong>
                </div>
              </div>
            </div>
            <div class="row mt-25">
              <div class="col-md-6 d-flex mt-sm-15">
                <div class="sidebar-icon-item">
                  <img src="{% static 'assets/imgs/page/job-single/job-type.svg' %}" alt="fiveM">
                </div>
                <div class="sidebar-text-info ml-10">
                  <span class="text-description jobtype-icon mb-10">Job type</span>
                  <strong class="small-heading">Permanent</strong>
                </div>
              </div>
              <div class="col-md-6 d-flex mt-sm-15">
                <div class="sidebar-icon-item">
                  <img src="{% static 'assets/imgs/page/job-single/deadline.svg' %}" alt="fiveM">
                </div>
                <div class="sidebar-text-info ml-10">
                  <span class="text-description mb-10">Deadline</span>
                  <strong class="small-heading">{{instance.deadline}}</strong>
                </div>
              </div>
            </div>
            <div class="row mt-25">
              <div class="col-md-6 d-flex mt-sm-15">
                <div class="sidebar-icon-item">
                  <img src="{% static 'assets/imgs/page/job-single/updated.svg' %}" alt="fiveM">
                </div>
                <div class="sidebar-text-info ml-10">
                  <span class="text-description jobtype-icon mb-10">Updated</span>
                  <strong class="small-heading">{{instance.post_date}}</strong>
                </div>
              </div>
              <div class="col-md-6 d-flex mt-sm-15">
                <div class="sidebar-icon-item">
                  <img src="{% static 'assets/imgs/page/job-single/location.svg' %}" alt="fiveM">
                </div>
                <div class="sidebar-text-info ml-10">
                  <span class="text-description mb-10">Location</span>
                  <strong class="small-heading">{{instance.city}}, {{instance.state}}, {{instance.country}}</strong>
                </div>
              </div>
            </div>
          </div>
          <div>

            {{ instance.description | safe }}
          </div>
          <div class="author-single">
            <span>{{instance.user.name}}</span>
          </div>
          <div class="single-apply-jobs">
            <div class="row align-items-center">
              <div class="col-md-5">
                <a class="btn action-button reload btn-default mr-15" href="{% url 'users:apply_job' pk=instance.pk %}" data-id="" data-text="{{confirm_apply_message}}" data-title="Are you sure?">Apply now</a>
                <a class="btn action-button-no-confirm no-popup reload btn btn-border" href="{% url 'users:save_job' pk=instance.pk %}">Save job</a>
              </div>
              <div class="col-md-7 text-lg-end social-share">
                <h6 class="color-text-paragraph-2 d-inline-block d-baseline mr-10">Share this</h6>
                <a class="mr-5 d-inline-block d-middle" href="{{ instance.user.facebook }}">
                  <img alt="fiveM" src="{% static 'assets/imgs/template/icons/share-fb.svg' %}" />
                </a>
                <a class="mr-5 d-inline-block d-middle" href="{{ instance.user.twitter }}">
                  <img alt="fiveM" src="{% static 'assets/imgs/template/icons/share-tw.svg' %}" />
                </a>
                <a class="mr-5 d-inline-block d-middle" href="{{ instance.user.werbsite }}">
                  <img alt="fiveM" src="{% static 'assets/imgs/template/icons/share-red.svg' %}" />
                </a>
                <a class="d-inline-block d-middle" href="{{ instance.user.instagram }}">
                  <img alt="fiveM" src="{% static 'assets/imgs/template/icons/share-whatsapp.svg' %}" />
                </a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-12 col-sm-12 col-12 pl-40 pl-lg-15 mt-lg-30">
          <div class="sidebar-border">
            <div class="sidebar-heading">
              <div class="avatar-sidebar">
                <figure>
                  {% if instance.user.file %}
                    <img alt="profile" id="avatar" src="{{ instance.user.file.url }}">
                  {% else %}
                    <img alt="profile" id="avatar" src="https://avatar.oxro.io/avatar.svg?name={{profile.name | default:'User'}}&background=3c65f5&caps=3&bold=true">
                  {% endif %}
                </figure>
                <div class="sidebar-info">
                  <span class="sidebar-company">{{instance.user.name}}</span>
                  <span class="card-location">{{instance.state}}, {{instance.country}}</span>
                  <a class="link-underline mt-15" href="#">{{ instance.user|get_jobs_count }} Open Jobs</a>
              </div>
              </div>
            </div>
            <div class="sidebar-list-job">
              <div class="box-map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2970.3150609575905!2d-87.6235655!3d41.886080899999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880e2ca8b34afe61%3A0x6caeb5f721ca846!2s205%20N%20Michigan%20Ave%20Suit%20810%2C%20Chicago%2C%20IL%2060601%2C%20Hoa%20K%E1%BB%B3!5e0!3m2!1svi!2s!4v1658551322537!5m2!1svi!2s" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
              </div>
              <ul class="ul-disc">
                <li>{{instance.city}}, {{instance.state}}, {{instance.country}}</li>
                <li>Phone: <a href="tel:{{instance.user.phone}}">{{instance.user.phone}}</a></li>
                <li>Email: <a href="mailto:{{instance.user.email}}">{{instance.user.email}}</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}

{% block static %}
{% load static %}

{% endblock %}