company/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = "company"

urlpatterns = [
    path('login/', views.company_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.company_signup, name="signup"),
    path('my-profile/', views.my_profile, name="my_profile"),
    path('photo-upload/', views.photo_upload, name="photo_upload"),
    path(
        'delete-avatar/',
        views.delete_avatar,
        name="delete_avatar"
    ),
    path('create-job/', views.create_post, name="create_post"),
    path('my-jobs/', views.my_posts, name="my_posts"),
    path('requests/', views.requests, name='request'),

    re_path(r'^my-jobs/(?P<pk>.*)/$', views.my_job, name="my_job"),
    re_path(r'^edit-job/(?P<pk>.*)/$', views.edit_post, name="edit_post"),
    re_path(r'^delete-job/(?P<pk>.*)/$', views.delete_job, name="delete_job"),
    re_path(
        r'^approve-request/(?P<pk>.*)/$',
        views.approve_request,
        name="approve_request"
    ),
    re_path(
        r'^decline-request/(?P<pk>.*)/$',
        views.decline_request,
        name="decline_request"
    ),
]

fiveM/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings
from main import views as general_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('web.urls', 'web')),
    path('app/', general_views.app, name='app'),

    path('app/accounts/', include('users.urls', namespace='users')),
    path('app/company/', include('company.urls', namespace='company')),

    re_path(
        'media/(?P<path>.*)$',
        serve,
        {'document_root': settings.MEDIA_ROOT}
    ),
    re_path(
        'static/(?P<path>.*)$',
        serve,
        {'document_root': settings.STATIC_FILE_ROOT}
    ),
]

users/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.enter, name="enter"),
    path('logout/', views.user_logout, name="user_logout"),
    path('edit/', views.edit_profile, name="edit_profile"),
    path('my-profile/', views.my_profile, name="my_profile"),
    path('photo-upload/', views.photo_upload, name="photo_upload"),
    path(
        'delete-avatar/',
        views.delete_avatar,
        name="delete_avatar"
    ),

    re_path(r'^save-job/(?P<pk>.*)/$', views.save_job, name="save_job"),
    re_path(r'^apply-job/(?P<pk>.*)/$', views.apply_job, name="apply_job"),
    re_path(r'^verify/(?P<pk>.*)/$', views.verify, name="verify"),
    re_path(r'^resend-otp/(?P<pk>.*)/$', views.resend_otp, name="resend_otp"),
]

web/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('contact-us/', views.contact, name="contact"),

    re_path(
        r'^job-details/(?P<pk>.*)/$',
        views.job_details,
        name="job_details",
    ),
]

templates/dashboard/auth_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="msapplication-TileColor" content="#0E0E0E">
    <meta name="template-color" content="#0E0E0E">
    <!-- <link rel="manifest" href="https://wp.alithemes.com/html/fiveM/demos/manifest.js' %}on" crossorigin> -->
    <meta name="msapplication-config" content="browserconfig.xml">
    <meta name="description" content="Index page">
    <meta name="keywords" content="index, page">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/imgs/template/favicon.svg' %}" />
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
    <title>{{title}} | fiveM</title>
  </head>
  <body>
    <div id="preloader-active">
      <div class="preloader d-flex align-items-center justify-content-center">
        <div class="preloader-inner position-relative">
          <div class="text-center"><img src="{% static 'assets/imgs/template/loading.gif' %}" alt="fiveM"></div>
        </div>
      </div>
    </div>
    <header class="header sticky-bar">
      <div class="container">
        <div class="main-header">
          <div class="header-left">
            <div class="header-logo"><a class="d-flex" href="{% url 'web:index' %}"><img alt="fiveM" src="{% static 'assets/imgs/template/jobhub-logo.svg' %}"></a></div>
          </div>
          <div class="header-nav">
            <nav class="nav-main-menu">
              <ul class="main-menu">
                <li><a class="{% if is_home %} active {% endif %}" href="{% url 'web:index' %}">Home</a></li>
                <li><a class="{% if is_about %} active {% endif %}" href="{% url 'web:about' %}">About Us</a></li>
                <li><a class="{% if is_contact %} active {% endif %}" href="{% url 'web:contact' %}">Contact Us</a></li>
              </ul>
            </nav>
            <div class="burger-icon burger-icon-white"><span class="burger-icon-top"></span><span class="burger-icon-mid"></span><span class="burger-icon-bottom"></span></div>
          </div>
          {% if request.user.is_authenticated %}
            <div class="header-right">
              <ul class="main-menu">
                <li class="dashboard">
                  <a  href="{% url 'app' %}">Dashboard</a>
                </li>
              </ul>
            </div>
          {% endif %}
      </div>
    </header>
    <div class="mobile-header-active mobile-header-wrapper-style perfect-scrollbar">
      <div class="mobile-header-wrapper-inner">
        <div class="mobile-header-content-area">
          <div class="perfect-scroll">
            <div class="mobile-search mobile-header-border mb-30">
              <form action="#">
                <input type="text" placeholder="Search…"><i class="fi-rr-search"></i>
              </form>
            </div>
            <div class="mobile-menu-wrap mobile-header-border">
              <!-- mobile menu start-->
              <nav>
                <ul class="mobile-menu font-heading">
                  <li><a class="{% if is_home %} active {% endif %}" href="{% url 'web:index' %}">Home</a></li>
                <li><a class="{% if is_about %} active {% endif %}" href="{% url 'web:about' %}">About Us</a></li>
                <li><a class="{% if is_contact %} active {% endif %}" href="{% url 'web:contact' %}">Contact Us</a></li>
                </ul>
              </nav>
            </div>
            {% if request.user.is_authenticated %}
            <div class="mobile-account">
              <h6 class="mb-10">Your Account</h6>
              <ul class="mobile-menu font-heading">
                <li><a href="{% url 'users:my_profile' %}">Profile</a></li>
                <li><a href="#">Work Preferences</a></li>
                <li><a href="#">Account Settings</a></li>
                <li><a href="#">Go Pro</a></li>
                <li><a href="{% url 'users:user_logout' %}">Sign Out</a></li>
              </ul>
            </div>
            {% endif %}
            <div class="mt-10 site-copyright">Copyright {% now 'Y' %} &copy; fiveM. <br> by fiveM </div>
          </div>
        </div>
      </div>
    </div>
    {% block content %}
    {% endblock %}


    <footer class="footer mt-50">
      <div class="container">
        <div class="row">
          <div class="footer-col-1 col-md-3 col-sm-12">
            <a style="display: block;" href="{% url 'web:index' %}"><img alt="fiveM" src="{% static 'assets/imgs/template/jobhub-logo.svg' %}"></a>
            <div class="mt-20 mb-20 font-xs color-text-paragraph-2">fiveM is the heart of the design community and the best resource to discover and connect with designers and jobs worldwide.</div>
            <div class="footer-social"><a class="icon-socials icon-facebook" href="#"></a><a class="icon-socials icon-twitter" href="#"></a><a class="icon-socials icon-linkedin" href="#"></a></div>
          </div>
          <div class="footer-col-2 col-md-2 col-xs-6">
            <h6 class="mb-20">Resources</h6>
            <ul class="menu-footer">
              <li><a href="#">About us</a></li>
              <li><a href="#">Our Team</a></li>
              <li><a href="#">Products</a></li>
              <li><a href="#">Contact</a></li>
            </ul>
          </div>
          <div class="footer-col-3 col-md-2 col-xs-6">
            <h6 class="mb-20">Community</h6>
            <ul class="menu-footer">
              <li><a href="#">Feature</a></li>
              <li><a href="#">Pricing</a></li>
              <li><a href="#">Credit</a></li>
              <li><a href="#">FAQ</a></li>
            </ul>
          </div>
          <div class="footer-col-4 col-md-2 col-xs-6">
            <h6 class="mb-20">Quick links</h6>
            <ul class="menu-footer">
              <li><a href="#">iOS</a></li>
              <li><a href="#">Android</a></li>
              <li><a href="#">Microsoft</a></li>
              <li><a href="#">Desktop</a></li>
            </ul>
          </div>
          <div class="footer-col-5 col-md-2 col-xs-6">
            <h6 class="mb-20">More</h6>
            <ul class="menu-footer">
              <li><a href="#">Privacy</a></li>
              <li><a href="#">Help</a></li>
              <li><a href="#">Terms</a></li>
              <li><a href="#">FAQ</a></li>
            </ul>
          </div>
          <div class="footer-col-6 col-md-3 col-sm-12">
            <h6 class="mb-20">Download App</h6>
            <p class="color-text-paragraph-2 font-xs">Download our Apps and get extra 15% Discount on your first Order&mldr;!</p>
            <div class="mt-15"><a class="mr-5" href="#"><img src="{% static 'assets/imgs/template/icons/app-store.png' %}" alt="fiveM"></a><a href="#"><img src="{% static 'assets/imgs/template/icons/android.png' %}" alt="fiveM"></a></div>
          </div>
        </div>
        <div class="footer-bottom mt-50">
          <div class="row">
            <div class="col-md-6"><span class="font-xs color-text-paragraph">Copyright &copy; {% now 'Y' %}. fiveM | All Rights Reserved</span></div>
            <div class="col-md-6 text-md-end text-start">
              <div class="footer-social"><a class="font-xs color-text-paragraph" href="#">Privacy Policy</a><a class="font-xs color-text-paragraph mr-30 ml-30" href="#">Terms &amp; Conditions</a><a class="font-xs color-text-paragraph" href="#">Security</a></div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <script src="{% static 'assets/js/vendor/jquery-3.5.0.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/modernizr-3.6.0.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery-migrate-3.3.0.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/waypoints.js' %}"></script>
    <script src="{% static 'assets/js/plugins/wow.js' %}"></script>
    <script src="{% static 'assets/js/plugins/magnific-popup.js' %}"></script>
    <script src="{% static 'assets/js/plugins/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/select2.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/isotope.js' %}"></script>
    <script src="{% static 'assets/js/plugins/scrollup.js' %}"></script>
    <script src="{% static 'assets/js/plugins/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/counterup.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>

    <script src="{% static 'js/script.js' %}"></script>
<!-- 
    <style>
      .btn.btn-default:hover {
        background-color: #1a385c;
        transform: translateY(-2px);
        transition: 0.2s;
      }
      .perfect-scroll{
        height: unset;
      }
      /* .mobile-header-wrapper-style{ */
        /* z-index: 1000; */
      /* } */
      /* .burger-icon{} */
      .header .main-header .header-right .member-login {
        display: inline-block;
        vertical-align: middle;
      }
      .header .main-header .header-right .member-login img {
        float: left;
        height: 35px;
        width: 35px;
        border-radius: 50%;
        margin: 0px 10px 0px 0px;
        vertical-align: middle;
      }
      .header .main-header .header-right .member-login .info-member {
        padding-left: 45px;
        text-align: left;
        line-height: 19px;
      }
      .header .main-header .header-right .member-login .info-member strong {
        display: block;
      }
      .dropdown {
        position: relative;
      }
      footer{
        -moz-box-shadow: 0 -1px 20px 0px rgb(59 101 245 / 40%);
        -webkit-box-shadow: 0 -1px 20px 0px rgb(59 101 245 / 40%);
        box-shadow: 0 -1px 20px 0px rgb(59 101 245 / 40%);
        padding: 40px 0 0;
        border-top-right-radius: 30px;
        border-top-left-radius: 30px;
      }
      .image-compay {
        position: absolute;
        top: -80px;
        left: 0px;
        width: 85px;
      }
      .image-compay image{
        display: block;
        width: 100%;
      }
      .selecty .selecty-selected{
        width: 100%;
        border: 2px solid #e0e6f6;
        border-radius: 4px;
        font-size: 14px;
        line-height: 22px;
        background: #fff;
        height: 53px;
        box-shadow: none;
        padding: 11px 15px 13px 20px;
        color: #a0abb8;
        display: flex;
        align-items: center;
        justify-content: space-between;
      }
      .preloader:not([class*="pl-"]){
        width: 100%;
      }
      .preloader {
        background-color: #fff;
        width: 100%;
        height: 100%;
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        z-index: 999999;
        transition: 0.6s;
        margin: 0 auto;
      }
      .align-items-center {
        align-items: center!important;
      }
      .justify-content-center {
        justify-content: center!important;
      }
      .d-flex {
        display: flex!important;
      }
      .position-relative {
        position: relative!important;
      }
      .text-center {
        text-align: center!important;
      }
      .preloader img {
        max-width: 250px;
      }
      .body-overlay-1 {
        background: transparent;
        height: 100%;
        left: 0;
        opacity: 0;
        position: fixed;
        top: 0;
        visibility: hidden;
        width: 100%;
        cursor: crosshair;
        z-index: 997;
      }
    </style> -->

    {% block static %}
    {% endblock %}
  </body>
</html>

templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="msapplication-TileColor" content="#0E0E0E">
    <meta name="template-color" content="#0E0E0E">

    <meta name="msapplication-config" content="browserconfig.xml">
    <meta name="description" content="Index page">
    <meta name="keywords" content="index, page">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'dashboard/assets/imgs/template/favicon.svg' %}">
    <link href="{% static 'dashboard/assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <title>{{title}} | fiveM</title>
  </head>
  <body>
    <div id="preloader-active">
      <div class="preloader d-flex align-items-center justify-content-center">
        <div class="preloader-inner position-relative">
          <div class="text-center"><img src="{% static 'dashboard/assets/imgs/template/loading.gif' %}" alt="fiveM"></div>
        </div>
      </div>
    </div>
    <header class="header sticky-bar"> 
      <div class="container">
        <div class="main-header">
          <div class="header-left">
            <div class="header-logo">
              <a class="d-flex" href="{% url 'company:dashboard' %}">
                <img alt="fiveM" src="{% static 'assets/imgs/template/jobhub-logo.svg' %}">
              </a>
            </div>
            <span class="btn btn-grey-small ml-10">Admin area</span>
          </div>
          <div class="header-search"> 
            <div class="box-search"> 
              <form action="">
                <input class="form-control input-search" type="text" name="keyword" placeholder="Search">
              </form>
            </div>
          </div>
          <div class="header-menu d-none d-md-block">
            <ul> 
              <li><a href="{% url 'web:index' %}">Home </a></li>
              <li> <a href="{% url 'web:about' %}">About us </a></li>
              <li> <a href="{% url 'web:contact' %}">Contact us</a></li>
            </ul>
          </div>
          <div class="header-right">
            <div class="block-signin">
                <a class="btn btn-default icon-edit hover-up" href="{% url 'company:create_post' %}">Post Job</a>
              <div class="dropdown d-inline-block">
                
                <ul class="dropdown-menu dropdown-menu-light dropdown-menu-end" aria-labelledby="dropdownNotify">
                  <li><a class="dropdown-item active" href="#">10 notifications</a></li>
                  <li><a class="dropdown-item" href="#">12 messages</a></li>
                  <li><a class="dropdown-item" href="#">20 replies</a></li>
                </ul>
              </div>
                <div class="dropdown d-inline-block member-login">
                    <b class="btn icon-down" id="dropdownProfile" type="button" data-bs-toggle="dropdown" aria-expanded="true" data-bs-display="static">
                        {% if profile.file %}
                            <img alt="profile" id="profilePic" src="{{ profile.file.url }}">
                        {% else %}
                            <img alt="profile" id="profilePic" src="https://avatar.oxro.io/avatar.svg?name={{profile.name | default:'User'}}&background=3c65f5&caps=3&bold=true">
                        {% endif %}
                        <div class="info-member"> 
                            <strong class="color-brand-1">{{ profile.name | default:'-'}}</strong>
                            <div class="dropdown">
                                <b class="font-xs color-text-paragraph-2">{{ current_role }}</b>
                            </div>
                        </div>
                    </b>
                    <ul class="dropdown-menu dropdown-menu-light dropdown-menu-end" aria-labelledby="dropdownProfile">
                        <li>
                            <a class="dropdown-item" href="{% url 'company:my_profile' %}">Profiles</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'users:user_logout' %}">Logout</a></li>
                    </ul>
                </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <div class="burger-icon burger-icon-white">
      <span class="burger-icon-top"></span>
      <span class="burger-icon-mid"></span>
      <span class="burger-icon-bottom"></span>
    </div>
    <div class="mobile-header-active mobile-header-wrapper-style perfect-scrollbar">
      <div class="mobile-header-wrapper-inner">
        <div class="mobile-header-content-area">
          <div class="perfect-scroll">
            <div class="mobile-search mobile-header-border mb-30">
              <form action="#">
                <input type="text" placeholder="Search…"><i class="fi-rr-search"></i>
              </form>
            </div>
            <div class="mobile-menu-wrap mobile-header-border">
              <!-- mobile menu start-->
              <nav>
                {% include 'dashboard/includes/nav.html' %}
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
    <main class="main">
      <div class="nav"><a class="btn btn-expanded"></a>
        <nav class="nav-main-menu">
            {% include 'dashboard/includes/nav.html' %}
        </nav>
        <div class="border-bottom mb-20 mt-20"></div>
      </div>
      <div class="box-content">
        <div class="box-heading">
          <div class="box-title"> 
            <h3 class="mb-35">{{title}}</h3>
          </div>
          <div class="box-breadcrumb"> 
            <div class="breadcrumbs">
              <ul> 
                <li> <a class="icon-home" href="{% url 'company:dashboard' %}">Admin</a></li>
                <li><span>{{title}}</span></li>
              </ul>
            </div>
          </div>
        </div>
        {% block content %}
        {% endblock %}

        {% if is_dashboard %}
        <div class="mt-10">
          <div class="section-box">
            <div class="container"> 
              <div class="panel-white pt-30 pb-30 pl-15 pr-15">
                <div class="box-swiper">
                  <div class="swiper-container swiper-group-10">
                    <div class="swiper-wrapper">
                      <div class="swiper-slide"> 
                        <img src="{% static 'dashboard/assets/imgs/page/dashboard/microsoft.svg' %}" alt="fiveM">
                      </div>
                      <div class="swiper-slide"> 
                        <img src="{% static 'dashboard/assets/imgs/page/dashboard/sony.svg' %}" alt="fiveM">
                      </div>
                      <div class="swiper-slide"> 
                        <img src="{% static 'dashboard/assets/imgs/page/dashboard/acer.svg' %}" alt="fiveM">
                      </div>
                      <div class="swiper-slide"> 
                        <img src="{% static 'dashboard/assets/imgs/page/dashboard/nokia.svg' %}" alt="fiveM">
                      </div>
                      <div class="swiper-slide"> 
                        <img src="{% static 'dashboard/assets/imgs/page/dashboard/asus.svg' %}" alt="fiveM">
                      </div>
                      <div class="swiper-slide"> 
                        <img src="{% static 'dashboard/assets/imgs/page/dashboard/casio.svg' %}" alt="fiveM">
                      </div>
                      <div class="swiper-slide"> 
                        <img src="{% static 'dashboard/assets/imgs/page/dashboard/dell.svg' %}" alt="fiveM">
                      </div>
                      <div class="swiper-slide"> 
                        <img src="{% static 'dashboard/assets/imgs/page/dashboard/panasonic.svg' %}" alt="fiveM">
                      </div>
                      <div class="swiper-slide"> 
                        <img src="{% static 'dashboard/assets/imgs/page/dashboard/vaio.svg' %}" alt="fiveM">
                      </div>
                      <div class="swiper-slide"> 
                        <img src="{% static 'dashboard/assets/imgs/page/dashboard/sony.svg' %}" alt="fiveM">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endif %}

        <footer class="footer mt-20">
          <div class="container">
            <div class="box-footer">
              <div class="row">
                <div class="col-md-6 col-sm-12 mb-25 text-center text-md-start">
                  <p class="font-sm color-text-paragraph-2">
                    Copyright &copy; {% now 'Y' %}. fiveM all right reserved
                  </p>
                </div>
                <div class="col-md-6 col-sm-12 text-center text-md-end mb-25">
                  <ul class="menu-footer">
                    <li><a href="{% url 'web:about' %}">About</a></li>
                    <li><a href="{% url 'web:contact' %}">Contact</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </footer>
      </div>
    </main>

    <script src="{% static 'dashboard/assets/js/vendor/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/vendor/modernizr-3.6.0.min.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/vendor/jquery-migrate-3.3.0.min.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/vendor/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/plugins/waypoints.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/plugins/magnific-popup.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/plugins/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/plugins/select2.min.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/plugins/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/plugins/jquery.circliful.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/main.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>

    {% block static %}
    {% endblock %}
  </body>
</html>

templates/dashboard/request.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load main_template_tags %}

{% block content %}
<div class="row"> 
  <div class="col-lg-12"> 
    <div class="section-box">
      <div class="container"> 
        <div class="panel-white mb-30">
          <div class="box-padding">
            <div class="row">
              {% for instance in instances %}
              <div class="col-xl-4 col-lg-4 col-md-6">
                <div class="card-grid-2 hover-up">
                  <div class="card-grid-2-image-left">
                    <div class="card-grid-2-image-rd online">
                      <a href="">
                        <figure>
                          {% if instance.profile.file %}
                            <img alt="profile" id="avatar" src="{{ instance.profile.file.url }}">
                          {% else %}
                            <img alt="profile" id="avatar" src="https://avatar.oxro.io/avatar.svg?name={{instance.profile.name | default:'User'}}&background=3c65f5&caps=3&bold=true">
                          {% endif %}
                        </figure>
                      </a>
                    </div>
                    <div class="card-profile pt-10"><a href="">
                        <h5>{{instance.profile.name}}</h5>
                      </a>
                      <span class="font-xs color-text-mutted">{{instance.job.job_title}}</span>
                      <div class="rate-reviews-small pt-5">
                        <span>
                          <img src="{% static 'assets/imgs/template/icons/star.svg' %}" alt="fiveM">
                        </span>
                        <span>
                          <img src="{% static 'assets/imgs/template/icons/star.svg' %}" alt="fiveM">
                        </span>
                        <span>
                          <img src="{% static 'assets/imgs/template/icons/star.svg' %}" alt="fiveM">
                        </span>
                        <span>
                          <img src="{% static 'assets/imgs/template/icons/star.svg' %}" alt="fiveM">
                        </span>
                        <span>
                          <img src="{% static 'assets/imgs/template/icons/star.svg' %}" alt="fiveM">
                        </span>
                        <!-- <span class="ml-10 color-text-mutted font-xs">(65)</span> -->
                      </div>
                    </div>
                  </div>
                  <div class="card-block-info">
                    <p class="font-xs color-text-paragraph-2">{{instance.profile.bio}}</p>
                    <div class="card-2-bottom card-2-bottom-candidate mt-30">
                      <div class="text-start">
                        {% for i in instance.job.skills|comma_separator %}
                        <a class="btn btn-tags-sm mb-10 mr-5" href="#">{{i}}</a>
                        {% endfor %}
                      </div>
                    </div>
                    <div class="employers-info mt-15" style="display: flex; align-items: center;justify-content: space-around;">
                      {% if instance.status == 'approved' %}
                        <strong style="color: #00c070;"> Approved </strong>
                      {% elif instance.status == 'declined' %}
                        <strong style="color: red;"> Declined </strong>
                      {% else %}
                        <a title="Decline" href="{% url 'company:decline_request' pk=instance.pk %}" data-id="{{instance.id}}" data-text="{{confirm_decline_message}}" data-title="Are you sure?" class="btn btn-default btn-brand icon-remove action-button no-popup reload">Decline</a>
                        <a title="Approve" href="{% url 'company:approve_request' pk=instance.pk %}" data-id="{{instance.id}}" data-text="{{confirm_approve_message}}" data-title="Are you sure?" class="btn btn-default btn-brand icon-tick action-button no-popup reload">Approve</a>
                      {% endif %}
                    </div>
                    <div class="employers-info align-items-center justify-content-center mt-15">
                      <div class="row">
                        <div class="col-6">
                          <span class="d-flex align-items-center">
                            <i class="fi-rr-marker mr-5 ml-0"></i>
                            <span class="font-sm color-text-mutted">{{ instance.job.city }}, {{ instance.job.country }}</span>
                          </span>
                        </div>
                        <div class="col-6">
                          <span class="d-flex justify-content-end align-items-center">
                            <i class="fi-rr-clock mr-5"></i>
                            <span class="font-sm color-brand-1">
                              ₹{{ instance.job.amnt_start_per_hrs|to_int }} - ₹{{ instance.job.amnt_end_per_hrs|to_int }}
                              <span class="hour">/hour</span>
                            </span>
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
            <!-- <div class="paginations">
              <ul class="pager">
                <li><a class="pager-prev" href="#"></a></li>
                <li><a class="pager-number" href="#">1</a></li>
                <li><a class="pager-number" href="#">2</a></li>
                <li><a class="pager-number" href="#">3</a></li>
                <li><a class="pager-number" href="#">4</a></li>
                <li><a class="pager-number" href="#">5</a></li>
                <li><a class="pager-number active" href="#">6</a></li>
                <li><a class="pager-number" href="#">7</a></li>
                <li><a class="pager-next" href="#"></a></li>
              </ul>
            </div> -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block static %}
{% load static %}

{% endblock %}